# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0002_auto_20170902_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='_token',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
