# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0003_auto_20170902_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(max_length=200, upload_to=b''),
        ),
    ]
