# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 23:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project1', '0004_auto_20170902_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='videoPublicado',
            field=models.FileField(default=django.utils.timezone.now, upload_to='videosPublicados/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='videoSubido',
            field=models.FileField(default=django.utils.timezone.now, upload_to='videosSubidos/'),
            preserve_default=False,
        ),
    ]
